# Generated by Django 2.2.17 on 2020-12-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('sex', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Sex')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('email', models.EmailField(blank=True, max_length=80, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Phone')),
                ('linkedin', models.URLField(blank=True, max_length=150, verbose_name='LinkedIn link')),
                ('image', models.ImageField(help_text='Please, the photo has to be square, e.g. 500x500', upload_to='members', verbose_name='Photo')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'cobija_member',
                'ordering': ['first_name'],
            },
        ),
    ]
