# Generated by Django 2.2.17 on 2020-12-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Role name')),
                ('description', models.TextField(blank=True, help_text='Description', verbose_name='Description')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Order')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'cobija_role',
                'ordering': ['order', 'name'],
            },
        ),
    ]
