# Generated by Django 2.2.17 on 2020-12-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20201224_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('sex', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Sex')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('email', models.EmailField(blank=True, max_length=80, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Address')),
                ('image', models.ImageField(help_text='Please, the photo has to be square, e.g. 500x500', upload_to='partners', verbose_name='Photo')),
                ('facebook', models.URLField(blank=True, max_length=150, verbose_name='Facebook link')),
                ('instagram', models.URLField(blank=True, max_length=150, verbose_name='Instagram link')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
                ('typepartner', models.ManyToManyField(to='core.TypePartner', verbose_name='Type of partner')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'cobija_partner',
                'ordering': ['first_name'],
            },
        ),
    ]
