# Generated by Django 2.2.17 on 2020-12-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20201224_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('sex', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Sex')),
                ('aproximated_age', models.CharField(max_length=50, verbose_name='Aproximated age')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('adopted', models.BooleanField(default=True, verbose_name='Adopted')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
                ('petcolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PetColor', verbose_name='Pet Color')),
                ('petsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PetSize', verbose_name='Pet Size')),
                ('typepet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TypePet', verbose_name='Type of pet')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'cobija_pet',
            },
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Reference image', upload_to='pets', verbose_name='Photo')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Pet photo',
                'verbose_name_plural': 'Pet photos',
                'ordering': ['photo'],
            },
        ),
    ]
